[pytest]
filterwarnings =
    ignore:.*Query.get\(\) method is considered legacy.*:sqlalchemy.exc.LegacyAPIWarning
    ignore:.*datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning
    ignore:.*openpyxl.*:DeprecationWarning
